"""
Django settings for Justchat project.

Generated by 'django-admin startproject' using Django 3.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import base64
import hashlib
import os
import sys
from django.contrib.auth.hashers import PBKDF2PasswordHasher

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-jj)01zg+0@oh18e)pu$l54%2=ml6l&2p^i-sy&=ys_zil7bl9z')

CHAT_FERNET_KEY = base64.urlsafe_b64encode(
    hashlib.sha256(SECRET_KEY.encode()).digest()[:32]
).decode()

DEBUG = os.environ.get('DEBUG', 'True').lower() in ('1', 'true', 'yes')

_allowed = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(',') if h.strip()] if _allowed else ['*']


# Application definition

INSTALLED_APPS = [
    'chat',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dj_rest_auth',
    'corsheaders',  

    'rest_framework',
    'rest_framework.authtoken',

    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'dj_rest_auth.registration',

    'allauth.socialaccount',

]

# https://stackoverflow.com/questions/49189402/auth-user-groups-fields-e304-reverse-accessor-for-user-groups-clashes-with
# https://stackoverflow.com/questions/26914022/auth-user-model-refers-to-model-that-has-not-been-installed
AUTH_USER_MODEL = 'chat.CustomUser'

AUTHENTICATION_BACKENDS = [
    # allauth specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
    # Needed to login by username in Django admin, regardless of allauth
    'django.contrib.auth.backends.ModelBackend',
]

SITE_ID = 1

REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'chat.api.serializers.CustomRegisterSerializer',
}



# https://www.rootstrap.com/blog/registration-and-authentication-in-django-apps-with-dj-rest-auth/
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'Justchat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Justchat.wsgi.application'
ASGI_APPLICATION = 'Justchat.asgi.application'

_redis_url = os.environ.get('REDIS_URL')
if _redis_url:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [_redis_url]},
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'},
    }

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
_db_url = os.environ.get('DATABASE_URL')
if _db_url:
    import dj_database_url

    DATABASES = {
        'default': dj_database_url.config(default=_db_url, conn_max_age=60),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


class FastPBKDF2PasswordHasher(PBKDF2PasswordHasher):
    iterations = 120000


PASSWORD_HASHERS = [
    'Justchat.settings.FastPBKDF2PasswordHasher',
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
] if (BASE_DIR / 'static').exists() else []
STORAGES = {
    'default': (
        {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
            'OPTIONS': {
                'access_key': os.environ.get('AWS_ACCESS_KEY_ID', ''),
                'secret_key': os.environ.get('AWS_SECRET_ACCESS_KEY', ''),
                'bucket_name': os.environ.get('AWS_STORAGE_BUCKET_NAME', ''),
                'endpoint_url': os.environ.get('AWS_S3_ENDPOINT_URL', ''),
                'region_name': os.environ.get('AWS_S3_REGION_NAME', 'auto'),
                    'addressing_style': os.environ.get('AWS_S3_ADDRESSING_STYLE', 'path'),
                'default_acl': os.environ.get('AWS_DEFAULT_ACL', 'private'),
                'querystring_auth': os.environ.get('AWS_QUERYSTRING_AUTH', 'false').lower()
                in ('1', 'true', 'yes'),
            },
        }
        if os.environ.get('AWS_STORAGE_BUCKET_NAME')
        and os.environ.get('AWS_S3_ENDPOINT_URL')
        and os.environ.get('AWS_ACCESS_KEY_ID')
        and os.environ.get('AWS_SECRET_ACCESS_KEY')
        else {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        }
    ),
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_UPLOAD_MAX_NUMBER_FILES = 50

_cors_origins = os.environ.get('CORS_ALLOWED_ORIGINS', '')
if _cors_origins:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(',') if o.strip()]
    CORS_ORIGIN_ALLOW_ALL = False
else:
    CORS_ALLOWED_ORIGINS = []
    CORS_ORIGIN_ALLOW_ALL = True
# https://django-allauth.readthedocs.io/en/latest/advanced.html
# https://django-allauth.readthedocs.io/en/latest/configuration.html

ACCOUNT_EMAIL_VERIFICATION ='none'
ACCOUNT_AUTHENTICATION_METHOD = 'username'
ACCOUNT_EMAIL_REQUIRED =False

# Email OTP verification (dev fallback)
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@localhost')
EMAIL_VERIFICATION_OTP_TTL_MINUTES = int(os.environ.get('EMAIL_VERIFICATION_OTP_TTL_MINUTES', '10'))
EMAIL_VERIFICATION_DELETE_AFTER_HOURS = int(os.environ.get('EMAIL_VERIFICATION_DELETE_AFTER_HOURS', '2'))

# https://github.com/Tivix/django-rest-auth/issues/502
# https://stackoverflow.com/questions/6800894/django-returns-403-error-when-sending-a-post-request
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'chat.authentication.EmailVerifiedTokenAuthentication',
        'chat.authentication.EmailVerifiedSessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    )
}

CSRF_COOKIE_NAME = 'XSRF-TOKEN'

CSRF_HEADER_NAME = 'HTTP_X_XSRF_TOKEN'

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

IMAGE_PROCESSING_API_BASE_URL = os.environ.get('IMAGE_PROCESSING_API_BASE_URL', 'http://127.0.0.1:3000').strip()

USER_SEARCH_BACKEND = os.environ.get('USER_SEARCH_BACKEND', 'opensearch')
OPENSEARCH_URL = os.environ.get('OPENSEARCH_URL', '')
OPENSEARCH_USER_INDEX = os.environ.get('OPENSEARCH_USER_INDEX', 'users')
USER_SEARCH_LIMIT_DEFAULT = 20

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'stream': sys.stdout,
        },
        'file_django': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'django.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 3,
            'formatter': 'verbose',
        },
        'file_chat': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'chat.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 3,
            'formatter': 'verbose',
        },
        'file_frontend': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'frontend.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 3,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_django'],
            'level': 'INFO',
        },
        'channels': {
            'handlers': ['console', 'file_chat'],
            'level': 'INFO',
            'propagate': False,
        },
        'chat': {
            'handlers': ['file_chat', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'frontend': {
            'handlers': ['file_frontend'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

