# Generated by Django 3.2.15 on 2022-10-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='admins',
            field=models.ManyToManyField(related_name='chat_admins', to='chat.Contact'),
        ),
    ]
