const API_BASE_URL = process.env.REACT_APP_API_BASE_URL || "http://127.0.0.1:8000";
const WS_BASE_URL = process.env.REACT_APP_WS_BASE_URL || "ws://127.0.0.1:8000";
const IMAGE_PROCESSING_BASE_URL = process.env.REACT_APP_IMAGE_PROCESSING_BASE_URL || "";

export { API_BASE_URL, WS_BASE_URL, IMAGE_PROCESSING_BASE_URL };

